//
//  Hexogram.m
//  iChing
//
//  Created by Linda Cobb on 7/25/12.
//  Copyright (c) 2012 __MyCompanyName__. All rights reserved.
//

#import "Hexogram.h"

@implementation Hexogram


@synthesize element1, element2;
@synthesize name;
@synthesize description;
@synthesize quote;
@synthesize advice;
@synthesize one, two, three, four, five, six;
@synthesize elementName1, elementName2;
@synthesize hexSymbol;




// text descriptions of each hex and the image files for the elements are defined here

-(id)getHexogram:(int)idNumber
{
	switch (idNumber) {
		case 1:
            self.hexSymbol = @"111111";
			self.element1 = @"heaven.png";
			self.element2 = @"heaven.png";
            self.elementName1 = @"Heaven";
            self.elementName2 = @"Heaven";
			self.name = @"Khien";
			self.description = @"(great and originating, creative)";
			self.quote = @"The world is but a canvas to the imagination. (Thoreau)";
			self.advice = @"This is a time when great creative power is available to you.";
			self.one = @"Darkness still. The dragon is lying hidden.  Remain patient. ";
			self.two = @"Light begins to emerge, the dragon appears in the field.  Meet him with modesty. ";
			self.three = @"Follow naturally flowing influence to that which is correct.  An active day, an apprehensive evening.";
			self.four = @"Let go of preconceived notions, there is the possibility of progress in many directions. ";
			self.five = @"It is advantageous to meet the dragon, your attention to proper principles aids you. ";
			self.six = @"Arrogance brings misfortune, the dragon exceeds proper limits.";
			break;
		case 2:
            self.hexSymbol = @"000000";
			self.element1 = @"earth.png"; 
			self.element2 = @"earth.png";
            self.elementName1 = @"Earth";
            self.elementName2 = @"Earth";
			self.name = @"Khwan";
			self.description = @"(great and originating, advantageous, receptive)";
			self.quote = @"Human salvation lies in the hands of the creatively maladjusted.";
			self.advice = @"Let your concerns drop away, follow someone else's lead.";
			self.one = @"The dragon treads through fallen leaves covered with frost.  Stop resisting and flow with events.";
			self.two = @"The solution is available and will appear with out repeated efforts.";
			self.three = @"Using your excellence, but under restraint, do what is right with out regard for popular opinion.";
			self.four = @"Danger, use reserve.  Things are tied up. Go with the flow.";
			self.five = @"Good fortune comes from doing what is right, not working to gain influence.";
			self.six = @"Dragons fighting, thoughts and actions of the ego should not be engaged in.";
			break;
		case 3:
            self.hexSymbol = @"100010";
			self.element1 = @"water.png"; 
			self.element2 = @"thunder.png";
            self.elementName1 = @"Water";
            self.elementName2 = @"Thunder";
			self.name = @"Kun";
			self.description = @"(caution at the beginning)";
			self.quote = @"The enlightened ruler is heedful, the good general full of caution.";
			self.advice = @"Allow obstacles to be removed rather than forcing your way through.";
			self.one = @"Difficult beginning, be correct and firm and stay the course.";
			self.two = @"A distressing return, but a solution appears.";
			self.three = @"Give up the chase and do not act on your own. Accept help and remain patient.";
			self.four = @"The lady seeks you, an union will meet with great fortune.";
			self.five = @"Do not force a completion.  Good fortune in small things, in great things trouble.";
			self.six = @"A forced retreat, you attempt to abandon your efforts.  Do not retreat, remain firm.";
			break;
		case 4:
            self.hexSymbol = @"010001";
			self.element1 = @"mountain.png";
			self.element2 = @"water.png";
            self.elementName1 = @"Mountain";
            self.elementName2 = @"Water";
			self.name = @"Mang";
			self.description = @"(youthful folly and inexperience)";
			self.quote = @"Seize the day, put no trust in tomorrow. (Horace)";
			self.advice = @"Find a wise teacher and like the child be open minded and learn.";
			self.one = @"Self discipline is required to gain mastery and dispell ignorance.";
			self.two = @"Be kind and gentle with the ignorant today.";
			self.three = @"Do not join with her, who will leave you for wealth.  Do not be servile in manner.";
			self.four = @"Regret comes to those who entangle themselves in the fears and fantasy of the ego.";
			self.five = @"Be as a child and seek truth openly without preconceived notions.";
			self.six = @"Be gentle in doling out punishments.  Punishments are necessary teaching tools.";
			break;
		case 5:
			self.element1 = @"water.png"; 
			self.element2 = @"heaven.png";
            self.elementName1 = @"Water";
            self.elementName2 = @"Heaven";
			self.name = @"Hsu";
			self.description = @"(firmness, waiting)";
			self.quote = @"When your work speaks for itself don't interrupt. (Kaiser)";
			self.advice = @"Be patient and quiet. Trust that things will be right.";
			self.one = @"The challenge is on the horizon. Wait, deepen the stillness inside.";
			self.two = @"Danger approaches, you will be spoken against, do not act rashly.";
			self.three = @"There is danger of being pulled into the current and injured.  Use proper principles.";
			self.four = @"Great danger spills blood.  Hospitals are close.";
			self.five = @"A moment of peace, time to eat and relax.";
			self.six = @"Three guests appear, the solution sounds strange. Accept the truth.";
			break;
		case 6:
            self.hexSymbol = @"111010";
			self.element1 = @"heaven.png"; 
			self.element2 = @"water.png";
            self.elementName1 = @"Heaven";
            self.elementName2 = @"Water";
			self.name = @"Sung";
			self.description = @"(conflict, opposition and obstruction)";
			self.quote = @"He who angers you conquers you. (Kenny)";
			self.advice = @"This is a time of conflict. You need to disengage yourself from it.";
			self.one = @"Conflict is about you, in the end good fortune will prevail.";
			self.two = @"The opponent is stronger.  Lie low and wait.";
			self.three = @"Do not climb the pedestal but work in the shadows.";
			self.four = @"Remain on the correct path, now is a time for study.";
			self.five = @"You will be a successful contender if you let the arbitrator aid you.";
			self.six = @"A success is gained but at a  great price.  Let it go and save yourself the price.";
			break;
		case 7:
            self.hexSymbol = @"010000";
			self.element1 = @"earth.png";
			self.element2 = @"water.png";
            self.elementName1 = @"Earth";
            self.elementName2 = @"Water";
			self.name = @"Sze";
			self.description = @"(a military leader)";
			self.quote = @"Do not wait for leaders, do it alone. (Mother Teresa)";
			self.advice = @"Conduct of oneself is of utmost importance now.";
			self.one = @"If you go forth with the ego, disaster comes.";
			self.two = @"Good fortune comes if you follow the wise leader.";
			self.three = @"Inferior aids to the leader abound.";
			self.four = @"Disengage and retreat, there is no error.  Success will follow.";
			self.five = @"Evil is in the open, do not follow the young leader however correct he is.";
			self.six = @"Small men should not be assigned, for immodest behavior leads to great humility.";
			break;
		case 8:
            self.hexSymbol = @"000010";
			self.element1 = @"water.png"; 
			self.element2 = @"earth.png";
            self.elementName1 = @"Water";
            self.elementName2 = @"Earth";
			self.name = @"Pi";
			self.description = @"(holding together, re-examination)";
			self.quote = @"We must live together as brothers or perish together as fools.";
			self.advice = @"A time for unions. Be willing to share.";
			self.one = @"A genuine commitment and sincerity seals the union.";
			self.two =  @"The way is not yet but almost open for the union.";
			self.three = @"Be wary of the unions you seek, they are not the right ones.";
			self.four = @"Seek unions beyond oneself and great success will follow.";
			self.five = @"There are several paths, allow your partner the freedom to pick one.";
			self.six = @"Proceed slowly and with great caution.";
			break;
		case 9:
            self.hexSymbol = @"111011";
			self.element1 = @"wind.png"; 
			self.element2 = @"heaven.png";
            self.elementName1 = @"Wind";
            self.elementName2 = @"Heaven";
			self.name = @"Hsiao";
			self.description = @"(the taming, clouds on the horizon)";
			self.quote = @"Every problem has a gift for you in its hands. (Bach)";
			self.advice = @"There are dark clouds on the horizon but the storm will soon pass.";
			self.one = @"It is good to pursue your own course, but do not force changes.";
			self.two = @"Return to the original course, the other way is closed.";
			self.three = @"Do not hurry things. Husbands and wives avoid each other's eyes.";
			self.four = @"Treat others with dignity and gentleness to avoid bloodshed.";
			self.five = @"Sincerity inspires others to be loyal to you and aid in your cause.";
			self.six = @"Be virtuous and tread slowly the wife is in danger.";
			break;
		case 10:
            self.hexSymbol = @"110111";
			self.element1 = @"heaven.png";
			self.element2 = @"lake.png";
            self.elementName1 = @"Heaven";
            self.elementName2 = @"Lake";
			self.name = @"Li";
			self.description = @"(treading on the tail of the tiger)";
			self.quote = @"No legacy is so rich as honesty. (Shakespeare)";
			self.advice = @"Now grab the tail of the tiger and tame inferior forces inside.";
			self.one = @"Stay on the current path, restlessness leads to troubles.";
			self.two = @"Tread a path with out entanglement on it.";
			self.three = @"False bravado leads to troubles, the tide rises and ebbs as it should.";
			self.four = @"Move easily but carefully, the tail you tread on is a kitten not a tiger.";
			self.five = @"There is peril about, but allow others to discover their way.";
			self.six = @"A warning appears, be sure to look at the whole of things, not the parts.";			
			break;
		case 11:
            self.hexSymbol = @"111000";
			self.element1 = @"earth.png";
			self.element2 = @"heaven.png";
            self.elementName1 = @"Earth";
            self.elementName2 = @"Heaven";
			self.name = @"Thai";
			self.description = @"(peace, good fortune)";
			self.quote = @"Following the light of the sun, we left the old world. (Columbus)";
			self.advice = @"A good time to sink down strong roots and allow yourself to grow.";
			self.one = @"A good time to pull your roots and make a move.";
			self.two = @"Be comfortable dealing with difficulties and difficult people.";
			self.three = @"Life flows and ebbs like the tides of the ocean.";
			self.four = @"Others come to your aid with sincerity, meet them with the same.";
			self.five = @"Remain patient and things will come to pass.";
			self.six = @"Troubles are coming, scheme not to escape them, but rather deal with them straight.";
			break;
		case 12:
            self.hexSymbol = @"000111";
			self.element1 = @"heaven.png"; 
			self.element2 = @"earth.png";
            self.elementName1 = @"Heaven";
            self.elementName2 = @"Earth";
			self.name = @"P'i";
			self.description = @"(standstill, rise of lower classes)";
			self.quote = @"Life will be brought to a standstill. (Nemwang)";
			self.advice = @"A time of stagnation. Work on the internal, do not get frustrated.";
			self.one = @"This is not the time for influence, withdraw while you can.";
			self.two = @"Be patient with mediocre people and parts of yourself.";
			self.three = @"There is shame of yourself in this purpose.";
			self.four = @"Act correctly and fortune will follow.";
			self.five = @"Change is at hand, but fear not.";
			self.six = @"The standstill is about to pass and good will follow.";
			break;
		case 13:
            self.hexSymbol = @"101111";
			self.element1 = @"heaven.png"; 
			self.element2 = @"fire.png";
            self.elementName1 = @"Heaven";
            self.elementName2 = @"Fire";
			self.name = @"Thung Zan";
			self.description = @"(fellowship, progress, success)";
			self.quote = @"Hell hath no fury like a bureaucrat scorned. (Friedman)";
			self.advice = @"This isn't a time for love triangles or deception in relationships.";
			self.one = @"Hidden agendas prevent unions of the masses.";
			self.two = @"Be wary of kindred meeting with groups and dividing into factions.";
			self.three = @"Secrets are withheld causing mistrust.";
			self.four = @"This is a time to separate rather than attack.";
			self.five = @"Stay with the leader of the union who expresses charm and deep feelings in a speech.";
			self.six = @"The leader travels to outer providence.";
			break;
		case 14:
            self.hexSymbol = @"111101";
			self.element1 = @"fire.png";
			self.element2 = @"heaven.png";
            self.elementName1 = @"Fire";
            self.elementName2 = @"Heaven";
			self.name = @"Ta Yu";
			self.description = @"(possession in great measure)";
			self.quote = @"No bird soars too high if he soars with his own wings. (Blake)";
			self.advice = @"Time of success, clarity and possession. Be generous.";
			self.one = @"Peace of mind is challenged but there is no approach to what is evil.";
			self.two = @"This is a safe time to relocate valuables.";
			self.three = @"The rich man (in self and possessions) gives what the poor man cannot.";
			self.four = @"Do not try to keep up with the Jones.  Hold and protect what is yours.";
			self.five = @"Do not chase others let them come to you.";
			self.six = @"Great fortune.";
			break;
		case 15:
            self.hexSymbol = @"001000";
			self.element1 = @"earth.png"; 
			self.element2 = @"mountain.png";
            self.elementName1 = @"Earth";
            self.elementName2 = @"Mountain";
			self.name = @"Khien";
			self.description = @"(modesty, humbleness)";
			self.quote = @"Of those who say nothing few are silent. (Neill)";
			self.advice = @"Humbleness inspires others to aid you and fortune to come your way.";
			self.one = @"Be modest about modesty and add more modesty to yourself.";
			self.two = @"Your fortune in in direct proportion to your modesty.";
			self.three = @"A successful person of merit pauses not at progress or anticipation of results.";
			self.four = @"Act in a correct, modest way for the benefit of all.";
			self.five = @"A time to move forward with arms, those around you will aid you.";
			self.six = @"Moving without modesty will harm those who aid you.";
			break;
		case 16:
            self.hexSymbol = @"000100";
			self.element1 = @"thunder.png";
			self.element2 = @"earth.png";
            self.elementName1 = @"Thunder";
            self.elementName2 = @"Earth";
			self.name = @"Yu";
			self.description = @"(enthusiasm, action)";
			self.quote = @"He who hesitates is a damn fool. (West)";
			self.advice = @"Choose openings that are right, don't let enthusiasm carry you.";
			self.one = @"False enthusiasm leads to trouble.";
			self.two = @"Be firm in your action, once you are sure it is correct.";
			self.three = @"Do not rely on favors from others.";
			self.four = @"Others join you now, be not suspicious of them.";
			self.five = @"A small illness, but not death.";
			self.six = @"Dark desires lead to troubles.";
			break;
		case 17:
            self.hexSymbol = @"100110";
			self.element1 = @"lake.png"; 
			self.element2 = @"thunder.png";
            self.elementName1 = @"Lake";
            self.elementName2 = @"Thunder";
			self.name = @"Sui";
			self.description = @"(following)";
			self.quote = @"What you do speaks so loudly that I cannot hear what you say. (Emerson)";
			self.advice = @"Practice what you preach and others will follow you.";
			self.one = @"Seek truth from outside your normal group of confidants.";
			self.two = @"Cling not to the things of youth but accept the treasures that come with age.";
			self.three = @"Keep the joys of youth while accepting the responsibilities of age.";
			self.four = @"This is a time to follow rather than to lead.";
			self.five = @"The leader brings out what is good in us, leading us to success.";
			self.six = @"Maintain loyalty.";
			break;
		case 18:
            self.hexSymbol = @"011001";
			self.element1 = @"mountain.png"; 
			self.element2 = @"wind.png";
            self.elementName1 = @"Mountain";
            self.elementName2 = @"Wind";
			self.name = @"Ku";
			self.description = @"(wait 3 days, spoilage)";
			self.quote = @"No man is ever old enough to know better. (Jackson)";
			self.advice = @"There is a defect around you that must be sought out and corrected.";
			self.one = @"Old family ways bring troubles that are fixed by the young generation.";
			self.two = @"A fear brought by an old women is conquered by the child.";
			self.three = @"A child fixes troubles brought by the father, be not too vigorous in this.";
			self.four = @"Tolerating wrong in elders brings troubles.";
			self.five = @"You are only obligated to fix your own doings, not others.";
			self.six = @"One who attends to his/her own affairs, apathy.";
			break;
		case 19:
            self.hexSymbol = @"110000";
			self.element1 = @"earth.png";
			self.element2 = @"lake.png";
            self.elementName1 = @"Earth";
            self.elementName2 = @"Lake";
			self.name = @"Lin";
			self.description =@"(approach, evil arrives in 8 months)";
			self.quote = @"There is no substitute for hard work. (Edison)";
			self.advice = @"This is a time of growth and there is a promise of light dawning.";
			self.one = @"A higher position is obtained through correct attitudes not ambition.";
			self.two = @"A promotion occurs in your work through alliance with your superior.";
			self.three = @"A pleasing step up but one that is not advantageous, danger of relapsing.";
			self.four = @"Progression to the highest position, by encouraging the abilities of others.";
			self.five = @"Gains in wisdom come from working with others.";
			self.six = @"Gains in honesty and generosity bring successes.";
			break;
		case 20:
            self.hexSymbol = @"000011";
			self.element1 = @"wind.png";
			self.element2 = @"earth.png";
            self.elementName1 = @"Wind";
            self.elementName2 = @"Earth";
			self.name = @"Kwan";
			self.description = @"(just prior to action, contemplation)";
			self.quote = @"To contemplation's sober eye, such is the race of man. (Gray)";
			self.advice = @"Through concentration and mediation you draw energy to you.";
			self.one = @"Your underlings don't blame you, your superiors have reason to regret.";
			self.two = @"Take things lightly, and watch.";
			self.three = @"Look over the effects of your life on others.";
			self.four = @"It is to your benefit to accept an invitation from one higher than you.";
			self.five = @"Contemplation of your life's course brings corrections.";
			self.six = @"Being blameless gains the world, contemplate your self and see that you are blameless.";
			break;
		case 21:
            self.hexSymbol = @"100101";
			self.element1 = @"fire.png";
			self.element2 = @"thunder.png";
            self.elementName1 = @"Fire";
            self.elementName2 = @"Thunder";
			self.name = @"Shih Ho";
			self.description = @"(use legal constraints)";
			self.quote = @"He who dies with the most toys is, nonetheless, still dead. (ukn)";
			self.advice = @"Serious misfortune occurs with distraction. Forgive but don't forget.";
			self.one = @"You are in the stockade, learning from your first mistake would've prevented this.";
			self.two = @"Treading into others privacy arouses anger and indignation.";
			self.three = @"Withdraw rather than attend disagreeable meetings.";
			self.four = @"Only the scraps are left, one must preserver.";
			self.five = @"Gold is hidden in others rubbish.";
			self.six = @"Obstinateness and refusing to listen result in embarrassment.";
			break;
		case 22:
            self.hexSymbol = @"100101";
			self.element1 = @"mountain.png";
			self.element2 = @"fire.png";
            self.elementName1 = @"Mountain";
            self.elementName2 = @"Fire";
			self.name = @"Pi";
			self.description = @"(free course, grace)";
			self.quote = @"Man was predestined to have free will. (Luyah)";
			self.advice = @"Let go of the bullying temptations and carry yourself with grace.";
			self.one = @"Go slowly, use older ways rather than machinery and technology.";
			self.two = @"Adorning oneself with jewels doesn't hide what lies beneath.";
			self.three = @"You are being adorned by others with jewels, do not become arrogant.";
			self.four = @"Money doesn't buy class, others will see through your falsity.";
			self.five = @"You wear silk and are surrounded by gardens but simplicity is a far greater thing.";
			self.six = @"Grace and strength come through simplicity.";
			break;
		case 23:
            self.hexSymbol = @"000001";
			self.element1 = @"mountain.png";
			self.element2 = @"earth.png";
            self.elementName1 = @"Mountain";
            self.elementName2 = @"Earth";
			self.name = @"Po";
			self.description = @"(stay put, wait, there is splitting apart)";
			self.quote =  @"Everything comes to him who hustles while he waits. (Edison)";
			self.advice = @"Keep still and quiet and be firm in your foundation.";
			self.one = @"Don't follow grievances and attack the foundations of great things.";
			self.two = @"If you are unyielding the skeleton of something great will be destroyed.";
			self.three = @"Stay with the traditional rather than the overthrowers.";
			self.four = @"Resistance if futile, rest and regroup.";
			self.five = @"You are the leader and bring quick changes of directions in the masses.";
			self.six = @"Beware of serpents with apples.";
			break;
		case 24:
            self.hexSymbol = @"100000";
			self.element1 = @"earth.png";
			self.element2 = @"thunder.png";
            self.elementName1 = @"Earth";
            self.elementName2 = @"Thunder";
			self.name = @"Fu";
			self.description = @"(return in 7 days, freedom of movement)";
			self.quote = @"Diamonds aren't more than chunks of coal that stuck to their jobs."; 
			self.advice = @"Rest now, the turning point has been reached.";
			self.one = @"A small error will not deviate you on the path of goodness.";
			self.two = @"Good fortune when you return, if you do not indulge in pride.";
			self.three = @"Repeated returns and fickleness slow you down.";
			self.four = @"Moving in the center, not relying on others opinions returns you to the proper path.";
			self.five = @"Return and take responsibility for, and correct your mistakes.";
			self.six = @"Confusion on the subject of returning wastes opportunities.";
			break;
		case 25:
            self.hexSymbol = @"100111";
			self.element1 = @"heaven.png";
			self.element2 = @"thunder.png";
            self.elementName1 = @"Heaven";
            self.elementName2 = @"Thunder";
			self.name = @"Wu Wang";
			self.description =@"(innocence, the unexpected, sit tight)";
			self.quote = @"There is no aphrodisiac like innocence. (Baudrillard)";
			self.advice = @"The unexpected should be enjoyed, not feared.";
			self.one = @"Freedom from insecurity allows you to remain detached and innocent.";
			self.two = @"It is the path not the result that matters, value the plowing more than the reaping.";
			self.three = @"Calamity occurs that is not of your own making, later rescue by a stranger saves you.";
			self.four = @"Remain firm and don't be persuaded by others, then there will be no error.";
			self.five = @"Remain disengaged when trouble comes and the illness will pass quickly.";
			self.six = @"Do not take action if you are sincere, accept what comes.";
			break;
		case 26:
            self.hexSymbol = @"111001";
			self.element1 = @"mountain.png";
			self.element2 = @"heaven.png";
            self.elementName1 = @"Mountain";
            self.elementName2 = @"Heaven";
			self.name = @"Ta Khu";
			self.description = @"(enjoy time with family)";
			self.quote = @"Cherish your human connections. (Bush)";
			self.advice = @"Find the strength within yourself now to maintain a serenity.";
			self.one = @"Endure difficulty with restraint you are in a position of peril.";
			self.two = @"Do not struggle with your bindings, they will fall off when you use self-discipline.";
			self.three = @"A tough advance but you make progress restraining your inferiors.";
			self.four = @"Do not act out strong emotions.";
			self.five = @"Other weapons can be used, restrain your desires.";
			self.six = @"Progress as obstacles are removed.";
			break;
		case 27:
            self.hexSymbol = @"100001";
			self.element1 = @"mountain.png";
			self.element2 = @"thunder.png";
            self.elementName1 = @"Mountain";
            self.elementName2 = @"Thunder";
			self.name = @"I";
			self.description = @"(provide nourishment)";
			self.quote = @"Our lives are not in the lap of the gods, but in our cooks.";
			self.advice = @"Proper nourishment is needed to build and keep a fine mind and body.";
			self.one = @"Engaging in doubt and envy forces you to watch evil.";
			self.two = @"Do not look to lazy or weak people for nourishment.";
			self.three = @"Do not expect to be nourished by desire and pleasure.";
			self.four = @"Look with strong eyes and others will nourish you.";
			self.five = @"Do not go across the current.";
			self.six = @"A perilous position can be made safe but emulating goodness.";
			break;
		case 28:
            self.hexSymbol = @"011110";
			self.element1 = @"lake.png";
			self.element2 = @"wind.png";
            self.elementName1 = @"Lake";
            self.elementName2 = @"Wind";
			self.name = @"Ta kwo";
			self.description = @"(thin ice, movement in any direction is advantageous)";
			self.quote = @"Many a trip continues long after the movement has ceased. (Steinbeck)";
			self.advice = @"The wind that bends the trees makes them stronger.";
			self.one = @"Use great care when planning.";
			self.two = @"An old husband with a young wife brings about renewal.";
			self.three = @"A weak beam causes a dangerous time, great care is needed.";
			self.four = @"A beam is curving upwards, the foundation is not laid correctly.";
			self.five = @"An old wife with a young husband weakens things.";
			self.six = @"Boldly crossing the stream without heeding what is correct leads to drowning.";
			break;
		case 29:
            self.hexSymbol = @"010010";
			self.element1 = @"water.png";
			self.element2 = @"water.png";
            self.elementName1 = @"Water";
            self.elementName2 = @"Water";
			self.name = @"Khan";
			self.description = @"(the abysmal, sincerity)";
			self.quote = @"Only two things are infinite, the universe and human stupidity, and I'm not sure about the former.";
			self.advice = @"Like a river allow yourself to be carried along with the current.";
			self.one = @"Many small bad habits will lead you to a dark cavern.";
			self.two = @"You are in peril of falling into an abyss, go cautiously.";
			self.three = @"All is peril and unrest, any step leads to peril.";
			self.four = @"A great feast at which you are honored comes if you have followed the correct path.";
			self.five = @"Order will soon come if you stop striving.";
			self.six = @"You are tangled in thorns caused by your improper behavior.";
			break;
		case 30:
            self.hexSymbol = @"101101";
			self.element1 = @"fire.png";
			self.element2 = @"fire.png";
            self.elementName1 = @"Fire";
            self.elementName2 = @"Fire";
			self.name = @"Li";
			self.description = @"(docility, clinging)";
			self.quote = @"The road to a friends house is never long. (Danish proverb)";
			self.advice = @"Allow yourself some dependence on others.";
			self.one = @"If you rush you will move with confused steps. ";
			self.two = @"You are in a yellow place, use moderation.";
			self.three = @"Accept what comes and be not like the old man set in his ways.";
			self.four = @"An abrupt step troubles all, take small steps.";
			self.five = @"Tears flow, accept the necessity of adversity.";
			self.six = @"Only the leader is punished, root out inferiors.";
			break;
		case 31:
            self.hexSymbol = @"001110";
			self.element1 = @"lake.png";
			self.element2 = @"mountain.png";
            self.elementName1 = @"Lake";
            self.elementName2 = @"Mountain";
			self.name = @"Hsien";
			self.description = @"(a young lady, influence)";
			self.quote = @"Glory is fleeting, but obscurity is forever. (Bonaparte)";
			self.advice = @"An event that will be a strong influence, is heading your way.";
			self.one = @"You have your foot in the door.";
			self.two = @"Progress takes time walk don't run.";
			self.three = @"Don't hold to tightly to others, allow them to pass with out passing over you.";
			self.four =@"Abandon anxieties and ambition, there will be no occasion for repentance.";
			self.five = @"Be adaptable, be wary of lust.";
			self.six = @"Use actions not words, be careful what you speak of.";
			break;
		case 32:
            self.hexSymbol = @"011100";
			self.element1 = @"thunder.png";
			self.element2 = @"wind.png";
            self.elementName1 = @"Thunder";
            self.elementName2 = @"Wind";
			self.name = @"Hang";
			self.description = @"(movement is necessary, duration)";
			self.quote = @"If you don't know where you're going you will end up somewhere else.";
			self.advice = @"A change has occurred. Stay true to your path and your course.";
			self.one = @"That which is worthwhile comes slowly, enjoy the tranquil path.";
			self.two = @"Do not strive, boast there will not be a chance to repent.";
			self.three = @"You may be swayed by external circumstances and this will cause misfortune.";
			self.four = @"Concentrate on attitude rather than goals, or the game will be called off.";
			self.five = @"Virtue must be continuously maintained by the wife.";
			self.six = @"Do not be restless for constant change.";
			break;
		case 33:
            self.hexSymbol = @"001111";
			self.element1 = @"heaven.png";
			self.element2 = @"mountain.png";
            self.elementName1 = @"Heaven";
            self.elementName2 = @"Mountain";
			self.name = @"Thun";
			self.description = @"(retreat, but successful progress)";
			self.quote = @"Every exit is an entry somewhere. (Stoppard)\n";
			self.advice =@"Your best bet is to find a strong quiet shelter and wait.";
			self.one = @"You are in a perilous position, a lingering negative force is about.";
			self.two = @"Do not place demands on the universe, it is like holding an ox with a string.";
			self.three = @"The clamoring of your ego will bring humiliation, take care of your servants.";
			self.four = @"Competition strengthens the forces against you, retire gracefully.";
			self.five = @"Be firm when it is time to leave, retire in an admirable way.";
			self.six = @"Cheerfully accept your retirement.";
			break;
		case 34:
            self.hexSymbol = @"111100";
			self.element1 = @"thunder.png";
			self.element2 = @"heaven.png";
            self.elementName1 = @"Thunder";
            self.elementName2 = @"Heaven";
			self.name = @"Ta Kwang";
			self.description = @"(the power of the great)";
			self.quote = @"Military power wins battles, spiritual power wins wars. (Nietzsche)"; 
			self.advice = @"Be careful your new powers, or you will be without influence.";
			self.one = @"You wish to advance but are held back. Advancing now leads to evil.";
			self.two = @"Resistance is giving way and progress is made but with sorrow.";
			self.three = @"Banging your head on the wall only damages your head.";
			self.four = @"Quietly and steadily remove obstacles.  The gate will be open when you arrive.";
			self.five = @"Your ease of position weakens you.";
			self.six = @"Indiscriminate use of power weakens you, you are boxed in, realize the problem.";
			break;
		case 35:
            self.hexSymbol = @"000101";
			self.element1 = @"fire.png";
			self.element2 = @"earth.png";
            self.elementName1 = @"Fire";
            self.elementName2 = @"Earth";
			self.name = @"Bin";
			self.description = @"(3 interviews)";
			self.quote = @"Shoot for the moon. Even if you miss, you'll land among the stars.";
			self.advice = @"Do not rest on your gains or let your ego get too inflated.";
			self.one = @"Be confident and correct, things are not as bad as they seem.";
			self.two = @"Progress may be halted because another fails to act, you advance sorrowfully.";
			self.three =  @"Do not be too quick to conquer the darkness you may not be strong enough.";
			self.four = @"Misfortune to those that abandon correct ways, you only appear to advance.";
			self.five = @"Do not concern yourself with failure or success.";
			self.six = @"Be careful to punish only those who are rebellious, be not indiscriminate.";
			break;
		case 36:
            self.hexSymbol = @"101000";
			self.element1 = @"earth.png";
			self.element2 = @"fire.png";
            self.elementName1 = @"Earth";
            self.elementName2 = @"Fire";
			self.name = @"Ming I";
			self.description = @"(difficulty of position, darkening of the light)";
			self.quote = @"In the depths of winter I found I had an invincible summer in me.";
			self.advice = @"Like an eclipse, all is dark now but a bit of light. Nurture it.";
			self.one = @"Your ego will lead you to misfortune, people will be speaking of you.";
			self.two = @"You have been wounded by a dark force, but a trusted stead will save you.";
			self.three = @"You have found the source of the problem, but do not act too quickly or eagerly.";
			self.four = @"What you recognize to be evil must not be allowed to temp you.";
			self.five = @"Resist struggling an external darkness can not be escaped at this time.";
			self.six = @"The darkness has obscured all, hold true and you shall be successful.";
			break;
		case 37:
            self.hexSymbol = @"101011";
			self.element1 = @"wind.png";
			self.element2 = @"fire.png";
            self.elementName1 = @"Wind";
            self.elementName2 = @"Fire";
			self.name = @"Kia Zan";
			self.description = @"(the wife must be strong and correct for the family)";
			self.quote = @"Courage is the price that life exacts for granting peace. (Earhart)";
			self.advice = @"Begin at home to influence the world around you.";
			self.one = @"There must be firmness in the household.";
			self.two = @"Do not seek to influence others by force, take nothing upon yourself.";
			self.three = @"Harshness leads to misfortune, but maintain a firm rule.";
			self.four = @"Well being is a product of inner balance, there will be enrichment.";
			self.five = @"Disengage from one's inferiors and a superior will take interest and aid you.";
			self.six = @"If you are correct in thoughts and sincere, you will be arrayed in majesty.";
			break;
		case 38:
            self.hexSymbol = @"110101";
			self.element1 = @"fire.png";
			self.element2 = @"lake.png";
            self.elementName1 = @"Fire";
            self.elementName2 = @"Lake";
			self.name = @"Khwei";
			self.description = @"(opposition, but success in small matters)";
			self.quote = @"We cannot change anything until we accept it.";
			self.advice = @"What's happening now, must happen in order for the future to unfold.";
			self.one = @"Do not try to create unity by force, a meeting with bad men will work out.";
			self.two = @"Opposition hinders a meeting of the minds, you may meet a lord in a passage.";
			self.three = @"Everything and everyone appear to conspire against you, you are turned back.";
			self.four = @"Mistrust of fate leaves you isolated but a man with sincere desires will work with you.";
			self.five = @"Misunderstanding cloaks the truth, a close union with a relative occurs.";
			self.six = @"Your relatives do not seek to harm you, lay aside mistrust";
			break;
		case 39:
            self.hexSymbol = @"001010";
			self.element1 = @"water.png";
			self.element2 = @"mountain.png";
            self.elementName1 = @"Water";
            self.elementName2 = @"Mountain";
			self.name = @"Kien";
			self.description = @"(go southwest and away from northeast)";
			self.quote = @"A friend is one who knows you and loves you just the same. (Hubbard)";
			self.advice = @"Seek the advice of a trusted person who is impartial.";
			self.one = @"This is a time retreat and observe, do not move forward.";
			self.two = @"You are struggling with difficulties not of your own doing.";
			self.three = @"Do not act recklessly remain in place.";
			self.four = @"Be still and a reunion will take place.";
			self.five = @"Perseverance will aid you and your friends arrive now to aid you.";
			self.six = @"Do not turn your back when you are needed, nor go forward at present.";
			break;
		case 40:
            self.hexSymbol = @"010100";
			self.element1 = @"thunder.png";
			self.element2 = @"water.png";
            self.elementName1 = @"Thunder";
            self.elementName2 = @"Water";
			self.name = @"Kieh";
			self.description = @"(deliverance found in southwest)";
			self.quote = @"Problems are only opportunities in work clothes. (Kaiser)";
			self.advice = @"Remember that difficult times occur to teach us lessons.";
			self.one = @"The obstacle is overcome, and there is no error.";
			self.two = @"Flattery prevents your movement, hunting will be successful.";
			self.three = @"Avoid the temptation to to be flashy and proud it will only attract robbers.";
			self.four = @"Friends will aid you when you free your self from internal and exterior inferiorities.";
			self.five = @"Superiors will remove the bad around you.";
			self.six = @"Aim high and success will come to you.";
			break;
		case 41:
            self.hexSymbol = @"110001";
			self.element1 = @"mountain.png";
			self.element2 = @"lake.png";
            self.elementName1 = @"Mountain";
            self.elementName2 = @"Lake";
			self.name = @"Sun";
			self.description = @"(decrease of two baskets of goods)";
			self.quote = @"Life is uncertain, eat desert first. (Ulmer)";
			self.advice = @"A time when things are not plentiful is at hand. This will pass.";
			self.one = @"Your affairs are put in suspension as you aid others.  Aid them without seeking fame.";
			self.two = @"Maintain your dignity now, and be still, action will lead to evil.";
			self.three = @"Walking with inferior ones prevents you from meeting an equal.";
			self.four = @"Your flaws lessen through work, and this draws others to you.";
			self.five = @"Generous offers are made and should not be refused.";
			self.six = @"Be generous and benevolent, more middle men appear than can be supported.";
			break;
		case 42:
            self.hexSymbol = @"100011";
			self.element1 = @"wind.png";
			self.element2 = @"thunder.png";
            self.elementName1 = @"Wind";
            self.elementName2 = @"Thunder";
			self.name = @"Yi";
			self.description = @"(increase)";
			self.quote = @"Riches are not an end of life, but an instrument of life. (Beecher)";
			self.advice = @"This is a time of plenty to be enjoyed.  Remember to make sacrifices for others and be generous.";
			self.one =  @"This is time to make a great movement, and do a good deed with your wealth.";
			self.two = @"Offers are made which can not be refused, pursue what is good.";
			self.three = @"You are recognized by your rank and uniform, be sure to use it to do correct things.";
			self.four = @"Your superior follows your advice, and you stay on course.";
			self.five = @"A generous heart seeks to benefit all, without seeking recognition.";
			self.six = @"None will aid you, many will assail you. ";
			break;
		case 43:
            self.hexSymbol = @"111110";
			self.element1 = @"lake.png";
			self.element2 = @"heaven.png";
            self.elementName1 = @"Lake";
            self.elementName2 = @"Heaven";
			self.name =  @"Kwai";
			self.description = @"(make public your resoluteness)";
			self.quote = @"If one does not know to where one is sailing, no wind is favorable.";
			self.advice = @"A breakthrough happens, remember that without resoluteness things will fall back.";
			self.one = @"You will go forward but not far.";
			self.two = @"Hostile measures are taken against you at night, you can prevail.";
			self.three = @"You will root out the evil, but be hated by your associates for doing so.";
			self.four = @"Punishment is accepted with out knowing why it is dealt, seek wise advice.";
			self.five = @"The small man must be uprooted and repositioned in the light.";
			self.six = @"There will be no help answering your call if you do not help the little men.";
			break;
		case 44:
            self.hexSymbol = @"011111";
			self.element1 = @"heaven.png";
			self.element2 = @"wind.png";
            self.elementName1 = @"Heaven";
            self.elementName2 = @"Wind";
			self.name = @"Kau";
			self.description = @"(coming to meet a strong female)";
			self.quote = @"The hardest thing is knowing which bridge to cross and which to burn.";
			self.advice = @"It is a dangerous time and the darkness is seductive.";
			self.one = @"Allow yourself to tied and chained, do not sub-come to temptations of the ego.";
			self.two = @"Much cash is on hand watch for unanticipated dangers. It will not do to have guests now.";
			self.three = @"Punishment is dealt out if you are provoked into a situation.  Remain calm.";
			self.four = @"An empty wallet leads you to restlessness, be still and calm.";
			self.five = @"Keep brilliance concealed.";
			self.six = @"Have guests now, but things are not resolved.";
			break;
		case 45:
            self.hexSymbol = @"000110";
			self.element1 = @"lake.png";
			self.element2 = @"earth.png";
            self.elementName1 = @"Lake";
            self.elementName2 = @"Earth";
			self.name = @"Bhui";
			self.description = @"(repairing the home a gathering together)";
			self.quote = @"Everywhere is with in walking distance if you have the time. (Wright)";
			self.advice = @"Great things begin with small steps.";
			self.one = @"A sincere desire for a union that can not happen leads to tears.";
			self.two = @"A dark impulse tempts you. Do not resist with violence and good fortune comes.";
			self.three = @"Still you strive after the union as others advise against, sighs not tears now.";  
			self.four = @"Others speak against your inferior qualities, with luck no blame comes.";
			self.five = @"A union of dignity comes with gentleness.";
			self.six = @"Sighing and weeping, withdraw and tolerate accusations.";
			break;
		case 46:
            self.hexSymbol = @"011000";
			self.element1 = @"earth.png";
			self.element2 = @"wind.png";
            self.elementName1 = @"Earth";
            self.elementName2 = @"Wind";
			self.name = @"Shang";
			self.description = @"(pushing upward, meeting with a great man)";
			self.quote = @"Progress comes from the intelligent use of experience. (Hubbard)";
			self.advice = @"Go around obstacles rather than fighting and great progress will be made.";
			self.one = @"Advancing with the welcome of others, do not hesitate to do what is correct.";
			self.two = @"With sincerity even small offerings are acceptable, others will join you.";
			self.three = @"One who desires reunion ascends upwards to an empty city with humiliation. ";
			self.four = @"A superior requests you to give a speech, work unselfishly.";
			self.five = @"You ascend the stairs, do not engage with minor influences. ";
			self.six = @"Blind advancement will cause lament, be sure in what you are doing.";
			break;
		case 47:
            self.hexSymbol = @"0010110";
			self.element1 = @"lake.png";
			self.element2 = @"water.png";
            self.elementName1 = @"Lake";
            self.elementName2 = @"Water";
			self.name = @"Khwan";
			self.description = @"(oppression, promises you make won't be kept)";
			self.quote = @"Never promise more than you can perform. (Syrus)";
			self.advice = @"A time of oppression and exhaustion, take care of yourself.";
			self.one = @"A long punishment in obscurity occurs if you do not correct things inside yourself.";
			self.two = @"Do not be pro-active, the superiors ministers come to you, do not be impatient.";
			self.three = @"Amid thorns you try to enter the palace;It is unwise to charge repeatedly a closed door.";
			self.four = @"You approach the wealthy, but fixed ideas will not gain their approval.";
			self.five = @"You will have no freedom of movement or information but you are content.";
			self.six = @"You are afraid to move, help arrives when you allow it to do so.";
			break;
		case 48:
            self.hexSymbol = @"011010";
			self.element1 = @"water.png";
			self.element2 = @"wind.png";
            self.elementName1 = @"Water";
            self.elementName2 = @"Wind";
			self.name = @"Bing";
			self.description = @"(the well, only the outside changes)";
			self.quote = @"If the facts don't fit the theory, change the facts. (Einstein)";
			self.advice = @"Drink from the well of inner strength and outer spirituality.";
			self.one = @"A muddy well with unpotable water serves no one.  Be right about yourself.";
			self.two = @"Neglect causes leaky well.";
			self.three = @"You know what is right but do not draw from the full well.";
			self.four = @"A well built well only appears to be good, first strengthen the walls.";
			self.five = @"A do not only draw from the well but drink.";
			self.six = @"A full well that is drawn from and used brings good fortune.";
			break;
		case 49:
            self.hexSymbol = @"101110";
			self.element1 = @"lake.png";
			self.element2 = @"fire.png";
            self.elementName1 = @"Lake";
            self.elementName2 = @"Fire";
			self.name = @"Ko";
			self.description = @"(seeing is believing, revolution)";
			self.quote = @"Sometimes things are true whether you believe in them or not.";
			self.advice = @"A time of revolution brings wonderful changes.";
			self.one = @"Persevere like the ox in innocence.";
			self.two = @"Changes are made after the ground work has been laid.";
			self.three = @"Position is perilous, move not in haste nor avoid all movement.";
			self.four = @"Ordinances are changed and you are blameless.";
			self.five = @"You change your stripes and faith is restored.  People support you now.";
			self.six = @"Spots change slowly as do inferior things.";
			break;
		case 50:
            self.hexSymbol = @"011101";
			self.element1 = @"fire.png";
			self.element2 = @"wind.png";
            self.elementName1 = @"Fire";
            self.elementName2 = @"Wind";
			self.name = @"Ting";
			self.description = @"(the caldron)";
			self.quote = @"It was deathly windy. I was just swirling at random. (Williams)";
			self.advice = @"Things swirl about as in a cauldron, be still.";
			self.one = @"The pot is overturned and the poison spilled out of it.";
			self.two = @"The cauldron is ready to be used, beware of envy of others.";
			self.three = @"Changes come, the meal is not eaten but fortune follows.";
			self.four = @"Good food ruined and humiliation follows.";
			self.five = @"Advance comes through being open and firm.";
			self.six = @"Lead others by example and good fortune will come your way.";
			break;
		case 51:
            self.hexSymbol = @"100100";
			self.element1 = @"thunder.png";
			self.element2 = @"thunder.png";
            self.elementName1 = @"Thunder";
            self.elementName2 = @"Thunder";
			self.name = @"Chen";
			self.description = @"(the arousing)";
			self.quote = @"Sour, sweet, bitter, pungent, all must be tasted. (Chinese proverb)";
			self.advice = @"Unsettling events disturb you. ";
			self.one = @"Look out with apprehension and then become comfortable with the shocking.";
			self.two = @"Give up your possessions and climb to a lofty height, peril is near, do not resist.";
			self.three = @"Be wary that distress from shock does not propel you to bad conduct.";
			self.four = @"You are sinking into the mud amidst startling movements, stop resisting what is coming.";
			self.five = @"You travel ad-mist the startling movements, stay centered and calm.";
			self.six = @"Engaging in shocking events draws relatives to speak against you.";
			break;
		case 52:
            self.hexSymbol = @"001001";
			self.element1 = @"mountain.png";
			self.element2 = @"mountain.png";
            self.elementName1 = @"Mountain";
            self.elementName2 = @"Mountain";
			self.name = @"Kan";
			self.description = @"(keeping still, see no evil, hear no evil)";
			self.quote = @"Never put off until tomorrow what you can do the day after tomorrow.";
			self.advice = @"Quiet your emotions.  Be still and unmoving like the mountain.";
			self.one = @"Be still this is a resting time.";
			self.two = @"There is much restlessness but remain still.";
			self.three = @"There is suppressed excitement while you rest, patience is needed.";
			self.four = @"Let your heart rest and your mind will rest.";
			self.five = @"Speak not, but rest.  A restless tongue betrays a restless mind.";
			self.six = @"Maintain peacefulness of mind and a noble heart.";
			break;
		case 53:
            self.hexSymbol = @"001011";
			self.element1 = @"wind.png";
			self.element2 = @"mountain.png";
            self.elementName1 = @"Wind";
            self.elementName2 = @"Mountain";
			self.name = @"Kien";
			self.description = @"(young lady brings developments, gradual progress)";
			self.quote = @"It is impossible to speak so that you cannot be misunderstood.";
			self. advice = @"Like a tree on a mountain without strong roots wind will uproot you.";
			self.one = @"A young officer in danger is spoken against, be not anxious or doubtful.";
			self.two = @"A safe haven is gradually approached.";
			self.three = @"Do not enter rashly into a conflict, especially if travel is involved.";
			self.four = @"Gently climb the tree and rest on its strong limbs.";
			self.five = @"As you climb the hill you are misunderstood, be patient, it will pass.";
			self.six = @"You gain the world if you keep to what is correct.";
			break;
		case 54:
            self.hexSymbol = @"110100";
			self.element1 = @"thunder.png";
			self.element2 = @"lake.png";
            self.elementName1 = @"Thunder";
            self.elementName2 = @"Lake";
			self.name = @"Kwei Mei";
			self.description = @"(sit tight, wait)";
			self.quote = @"Virtue herself is her own fairest reward. (Italicus)";
			self.advice = @"Social, romantic, work relationships must all be handled properly.";
			self.one = @"Like a sister is married off to be a 2nd wife you will have little influence.";
			self.two = @"Solitary widowhood is advantageous, be sure to keep up appearances.";
			self.three = @"Do not be lax and tempt fate.";
			self.four = @"Things that come slowly are more stable and valuable.";
			self.five = @"Learn as a second wife to be not envious to those above or disdainful of those below.";
			self.six = @"The basket will be empty unless your inner self is full of good things.";
			break;
		case 55:
            self.hexSymbol = @"101100";
			self.element1 = @"thunder.png";
			self.element2 = @"fire.png";
            self.elementName1 = @"Thunder";
            self.elementName2 = @"Fire";
			self.name = @"Fang";
			self.description = @"(abundance, rest easy)";
			self.quote = @"Abundance is not something we aquire it is something we tune into.";
			self.advice = @"Like a summer storm there is great power and danger.";
			self.one = @"A meeting occurs with a potentially influential mate.";
			self.two = @"Mistrust and envy must be seen through to have influence.";
			self.three = @"Influence is lost if one does not see through the darkness.";
			self.four = @"Insights occur and darkness gives way.";
			self.five = @"Men of brilliant ability surround you to aid you.";
			self.six = @"Improper use of abundance leaves you lonely.";
			break;
		case 56:
            self.hexSymbol = @"001101";
			self.element1 = @"fire.png";
			self.element2 = @"mountain.png";
            self.elementName1 = @"Fire";
            self.elementName2 = @"Mountain";
			self.name = @"Lu";
			self.description = @"(good fortune for the wanderer)";
			self.quote = @"Reject your sense of injury and the injury itself disappears.";
			self.advice = @"Behave as a traveler, settle disputes quickly and modestly.";
			self.one = @"A mean wanderer is about.";
			self.two = @"A wanderer at the lodging house with his servants and tools will attract friends.";
			self.three = @"The wanderer burns the lodging house by meddling.";
			self.four = @"The wanderer is at rest in body only, not at rest in his mind.";
			self.five = @"The bird is shot but the arrow is lost.";
			self.six = @"The wanderer laughs then cries out as the house is burned through carelessness.";
			break;
		case 57:
            self.hexSymbol = @"011011";
			self.element1 = @"wind.png";
			self.element2 = @"wind.png";
            self.elementName1 = @"Wind";
            self.elementName2 = @"Wind";
			self.name = @"Sun";
			self.description = @"(good time to see the boss)";
			self.quote = @"The 1st step to getting things you want is to decide what you want";
			self.advice = @"A wind that changes direction only stirs, not changes, things.";
			self.one = @"Advancement followed by a retreat.";
			self.two = @"Confusion from a hidden enemy dismays you.";
			self.three = @"Penetration occurs only after violent, repeated efforts.  Do not dwell there.";
			self.four = @"Hunting for game helps external difficulties pass.";
			self.five = @"Movements are advantageous, change for the better occurs.";
			self.six = @"The tool that executes decisions is lost, an inferior enemy is not easily seen.";
			break;
		case 58:
            self.hexSymbol = @"110110";
			self.element1 = @"lake.png";
			self.element2 = @"lake.png";
            self.elementName1 = @"Lake";
            self.elementName2 = @"Lake";
			self.name = @"Tui";
			self.description = @"(the joyous, lake)";
			self.quote = @"That government is best which governs the least.";
			self.advice = @"What is won by browbeating and force is seldom held long.";
			self.one = @"Pleasure of inward harmony comes from detachment.";
			self.two = @"Pleasure from inward sincerity can be destroyed by temptation.";
			self.three = @"Inward strength avoids troubles without.";
			self.four = @"Deliberation of what to take pleasure in, monetary or peace.";
			self.five = @"You trust in one who would injure you.";
			self.six = @"Do not lead others in the pleasures of the world but in inner pleasures.";
			break;
		case 59:
            self.hexSymbol = @"010011";
			self.element1 = @"wind.png";
			self.element2 = @"water.png";
            self.elementName1 = @"Wind";
            self.elementName2 = @"Water";
			self.name = @"Hwan";
			self.description = @"(dispersion, time to visit the childhood home)";
			self.quote = @"Our greatest glory is in rising every time we fall. ";
			self.advice = @"Rigidity and harshness are here, dissolve them with gentleness.";
			self.one = @"By healing misunderstandings quickly you rescue one from evil.";
			self.two = @"A moderate view of others short comings speeds you to security.";
			self.three = @"Disregarding your own safety in the short term brings long term gains.";
			self.four = @"Scattering all you sacrifice short term for long term.";
			self.five = @"A speech made in a sweat calms the scattering and brings others to you.";
			self.six = @"Bloody wounds are healed and you lead others to peace.";
			break;
		case 60:
            self.hexSymbol = @"110010";
			self.element1 = @"water.png";
			self.element2 = @"lake.png";
            self.elementName1 = @"Water";
            self.elementName2 = @"Lake";
			self.name = @"Kieh";
			self.description = @"(limitation but only temporarily)";
			self.quote = @"An ounce of prevention is worth a pound of cure. (Henry De Bracton)";
			self.advice = @"Be thrifty with funds as well as emotions. Keep things balanced.";
			self.one = @"Leaving the courtyard through the door you are constrained.";
			self.two = @"Seize your advantage by leaving the courtyard through the gate.";
			self.three = @"Follow regulations or you will be correcting your mistakes.";
			self.four = @"Accept limitations and regulations.";
			self.five = @"First follow your own regulations, then others will do so.";
			self.six = @"Avoid severely enforcing your regulations.";
			break;
		case 61:
            self.hexSymbol = @"110011";
			self.element1 = @"wind.png";
			self.element2 = @"lake.png";
            self.elementName1 = @"Wind";
            self.elementName2 = @"Lake";
			self.name = @"Kung Fu";
			self.description = @"(inner truth, movement is required)";
			self.quote = @"The unexamined life is not worth living. (Socrates)";
			self.advice = @"It is time to let emotions settle and to be receptive.";
			self.one = @"Rest and examine yourself now.";
			self.two = @"The young ones cry out because inner weaknesses are seen by others.";
			self.three = @"Your mate can not give you inner strength, there are tears and laughter.";
			self.four = @"The power is in you recognize this and you can use it.";
			self.five = @"Sincerity creates a close union.";
			self.six = @"Each must find his own way to heaven.png.";
			break;
		case 62:
            self.hexSymbol = @"001100";
			self.element1 = @"thunder.png";
			self.element2 = @"mountain.png";
            self.elementName1 = @"Thunder";
            self.elementName2 = @"Mountain";
			self.name = @"Hsiao Kwo";
			self.description = @"(preponderance of the small)";
			self.quote = @"Our patience will achieve more than out force. (Burke)";
			self.advice = @"Do not struggle or try to force changes, success comes by waiting.";
			self.one = @"A bird who flys too early is saved by evil.";
			self.two = @"Meetings occur with the rule, but it is not time for things to be resolved.";
			self.three = @"No precautions are taken against danger and injury results.";
			self.four = @"You will travel your planned course if you yield not to temptation to act harshly.";
			self.five = @"Dark clouds but no storm arrives.  Others aid you.";
			self.six = @"You press on force-ably and calamity results.";
			break;
		case 63:
            self.hexSymbol = @"101010";
			self.element1 = @"water.png";
			self.element2 = @"fire.png";
            self.elementName1 = @"Water";
            self.elementName2 = @"Fire";
			self.name = @"Ki Bi";
			self.description = @"(completion brings success)";
			self.quote = @"The best way to escape a problem is to solve it. (Saporta)";
			self.advice = @"A time of chaos has passed and things are settling into order.";
			self.one = @"The fox chasing his tail realizes not he goes in circles.";
			self.two = @"A protective cover is lost but re-found in a week or so.";
			self.three = @"The evil is attacked and loses but takes long to subdue.";
			self.four = @"Rags are used to hold the water out of the boat since we did not keep up repairs.";
			self.five = @"The small sincere sacrifice is greater than the large easy one.";
			self.six = @"Peril, admiring your reflection in the stream you will fall in.";
			break;
		case 64:
            self.hexSymbol = @"010101";
			self.element1 = @"fire.png";
			self.element2 = @"water.png";
            self.elementName1 = @"Fire";
            self.elementName2 = @"Water";
			self.name = @"Wei Bi";
			self.description = @"(disorder before completion)";
			self.quote = @"When I hear somebody sigh, Life is hard, I am always tempted to ask, Compared to what? (Harris)";
			self.advice = @"Winter is almost gone and spring approaches.  Be calm and conscientious, abandon hysterics.";
			self.one = @"Rapid progress leads to failure.";
			self.two = @"A temporary setback is easily fixed.";
			self.three = @"Good follows crossing the stream, a transition occurs.";
			self.four = @"Good fortune and rewards arrive if you do not waiver.";
			self.five = @"The brightness of a superior man leads you on the correct path.";
			self.six = @"Feasting and confidence must not undermine your displine.";
			break;
		default:
			break;
	}
	
	return self;
}





@end
